### ISSUE TITLE
Danger-free?

### ISSUE THREAD

**Issue by Dawnspire3000** [x0rz/EQGRP#10]
My Antivirus keeps putting certain binaries into quarantine. Does anyone use all the binaries? Are they really safe? I mean, this is legit but would that stop dangerous files from being in there?

**Comment by Chnkr** [comment]
Nothing in here is "danger free" if you are going to execute random binaries you downloaded from a random github repository you are going to be in a world of pain

**Comment by Dawnspire3000** [comment]
Well that's true but again, this appears to not just be some random repository. I just wanted to know if anyone had bad experiences with them or if its working fine

**Comment by peterpt** [comment]
Some of the binaries are probably to be planted on victim system and are not exploits .
This means that those binaries have already a backdoor implemented .

Other wise it makes no sense antivirus popup warnings on these files if they are only exploits .

**Comment by frankmusher** [comment]
Oh dear.

**Comment by Ekultek** [comment]
You should reverse engineer the binary first before you execute them

**Comment by Dawnspire3000** [comment]
Good idea, I'll work on it

**Comment by Tdog21** [comment]
As Ekultek said reverse engineering is a good idea, but take head as peterpt formentioned about executing random binaries on your machine as TAO standard procedure states they use a staging server to access their tools integrity and whether or not they need further development. I use an old Linux laptop to access and identify their functions. 

I do have Danderspritz on hand; specific binaries use LP (Listening Post) to connect to Implants. The NSA TAO branch seems to operate like the military and I do suppose it is directly tied too US Cyber command. I went through TAO SOP and to run any operations they have MIT install most of the prerequisites. A Solaris/Windows server 2008 standalone OS for FA servers. But I theorize they mainly use either Solaris or Apache according to the leak during August last year.

**Comment by Ekultek** [comment]
What you should really do if you don't want to take time to reverse engineer, is sandbox a virtual machine and run each one, make a custom app that will record all the differences made from start to finish and then figure out what each one does from there.

However what @Tdog21 said is a brilliant idea, but if you're just looking to get them run, sandbox it, run each one and discover the backtrace of what each one does.

**Comment by Tdog21** [comment]
@Ekultek I'm quite surprised you'd agree. The only issue is virtual boxes tend to be harder to work with due to their high memory usage and unreliability and Advanced Persistent threats can target the box. But I see you point.

**Comment by Ekultek** [comment]
@Tdog21 you are correct, but at the same time, you can always get rid of a VM and it's easier to do so then to completely reformat your hard drive. And with a sandbox around it, nothing will get out, unless as you said it's extremely advanced. Which in this case, most of them don't look to advanced

**Comment by Tdog21** [comment]
@Ekultek good point although I never mentioned its extremely advanced, for me doing it on a different machine allows me to listen to the machines port and see what going on. Plus I do have a slow internet connection where I live, So deleting a VM with up-to-date drivers and software isn't a option for me.

**Comment by Ekultek** [comment]
Fair enough, either way most of these scripts don't even work. I think we're missing something from them, to be honest. Either way none of this was made by the NSA lol

**Comment by Tdog21** [comment]
@Ekultek I might be able to provide insight into this question I'm doing a summer internship with their cyber division over the summer this year

**Comment by Ekultek** [comment]
@Tdog21  which question would that be? And how did you manage to land that internship?

**Comment by peterpt** [comment]
Most tools do a call to jl.command witch execute the compiled binary connect.so .
 
So , reversing the connect.so to original source code will give you an idea how the exploit works , or even if it is an exploit .

if you all look inside this example script : 
https://github.com/x0rz/EQGRP/blob/master/archive_files/bin/decftp.sh

at the end of the script jl.command executes that binary to a supposed port 10402 .
basically for what i can see , this tool will retrieve the file pmgrd.Z from a specific server after jl.command is executed .
And if you still look closely to the script , you will see that you already have to know the base directory to where this tool will get that data .

The data will be in an hidden directory inside your base directory that you must specify on executing the script .
Line 26 shows the location of hidden directory inside your base directory
line 32 start ftp and in line 36 is picked up the file from server .

I did not had much time yet to look into these tools more carefully , but you all should be carefull using any tool inside bin directory , because all of them make an execution call to jl.command which uses a pre-compiled binary with extension .so which we do not know noting about it .

**Comment by Tdog21** [comment]
@Ekultek I didn't "land it" yet I looked their their career and internship programs and I'm still deciding and

**Comment by Ekultek** [comment]
@Tdog21 what's there to decide man? That's an awesome opportunity, take it with both hands or someone else will bro! Imagine how much you already know, and then imagine what you could learn.

**Comment by Tdog21** [comment]
@Ekultek Good point I might as well apply

**Comment by Tdog21** [comment]
@peterpt good point and yes the NSA have their own file extensions for their CNE/CNA branch

**Comment by peterpt** [comment]
My guess to all these tools is that these tools should be executed inside victim machine and not from outside .

**Comment by Ekultek** [comment]
@peterpt either that or we're missing a distro server or something, executing these inside a machine doesn't really make sense, you would need to know the exact layout of their machine in order to work efficiently. However if you executed it from a server, then these might just be the tools to exploit the Cisco servers that got patched

**Comment by Ekultek** [comment]
So my guess is, these are either bullshit and they threw them together to scare someone, or, we're missing something. However Snowden himself did say something about these and we can't discredit (even though he's very unreliable) Snowden just yet.

**Comment by peterpt** [comment]
Ekultek , there could be mixed stuff .
We will know in next weeks .
When i get some time here i will look more closely , in mean while i believe that a new batch of files will be updated . Maybe some cool stuff come along on next batch of files .

**Comment by Ekultek** [comment]
I say fuck it guys. @peterpt @Tdog21 let's hack the NSA, give them a taste of their own medicine.

**Comment by peterpt** [comment]
hacking NSA exploit repository would be the same thing as winning the lottery .
Unless you worked there and you have a backdoor login , then it will be a very difficult job to hack them .
Most of what can be achieved to NSA is a ddos , but that will not take you anywhere .

Anyway , if you give a job to 2 persons where each person must do it individually , then you will get different results .
This mean many of the released 0day exploits on exploit-db , NSA did not know about them , they probably have a different approach to a specific program witch uses a different exploit technique .
Te difference between both is that 0day exploits on exploit-db are patched by software companies , while NSA are not patched because software companies do not know yet about that vulnerability .  
This way it gives NSA a very big leverage .
However , if you look into github codes you will see that many people create code to violate other persons privacy , while others on github build code to protect those persons .
Only this way i believe things can evolute in programming .

**Comment by Ekultek** [comment]
@peterpt well I work for the government, I can tell you this much, they are really big on keeping things secure and really like to find what's wrong with everyone else, but when they do find it, they don't really fix it for themselves. Example all those Cisco switches, they may have patched it for everyone else, but did they patch it for their government that didn't tell them about the exploits in the first place? They are under no legal binding contract to not patch them for the NSA. Just because something seems impossible doesn't mean it is. A 12 year old got 400k from Google for finding an exploit once.

**Comment by peterpt** [comment]
See it this way .
Got an open port , if you have an exploit for that service running on that port then you can get in and do whatever you want , otherwise forget it .
Usually hacking on the fly is done by SQL injection points on some webserver , but by default the good stuff is not on the same subnet of the webserver .
Without even mention that you have to route your connection to multiple proxys to not be detected , which these days it is not difficult to bypass to get your rel public ip address .
However , i believe that this subject should not be discussed here on github , but just to finish the comment , a good sysadmin never uses the original firmware of his router , firewall or switch , open source firmwares are the best solution in every perspective .
Again , by default Governments always use original firmwares on their network hardware , which make things more easier to hack .
Most sophisticated attacks to networks are made by multiple people at same time , where 2 or 3 are doing the job to get in while the other 17 are sending controlled dos attacks or testing the website just to fill up the firewall log so the work of those 3 could not be detected easily on realtime .
After those 3 or 1 of them get in , then the first thing they do is to clear the log file from firewall or server so the sysadmin have no idea how did they got inside , and then after their job is done on the victim , they clean the log again .
When sysadmin get a look into server or firewall logs , he will not find anything and at same time he was hacked .
Hackers using this technique , next time they will do it the same way they did before because that vulnerability that they found was not patched because sysadmin have no idea how did they do it .

**Comment by Tdog21** [comment]
@peterpt and you point is...

**Comment by Far00K** [comment]
But if you want to hack NSA you must find the vulnerability they found. If that was that you wanted? And if you want to clean the log you need admin that can take a while and the time you are trying to get root access they will already see the log. 

You need to get root access very fast... maybe do some Reconnasissance/ Footprinting and see how often they look on there system to see how much time you have. 

Or you hack them without making any strange so the sysadmin react and sees it

**Comment by Ekultek** [comment]
That's a valid point however, usually when you're in a system you only have a certain amount of time until you'll be caught. And the proxy thing, use a chain proxy with a VPN, and a Tor connection. Problem solved.

**Comment by Ekultek** [comment]
We should probably stop talking about hacking the NSA on an apparent NSA repo.

**Comment by Ekultek** [comment]
What I find the strangest is that all these scripts seem to have version numbers.. that indicates a type of VCS..

**Comment by Far00K** [comment]
That is a good idea

**Comment by Tdog21** [comment]
@Ekultek Lets not talk about hacking the NSA

**Comment by Far00K** [comment]
ya... for example eleganteagle-1.0.0.3, eleganteagle-1.0.0.3

**Comment by Far00K** [comment]
I mean eleganteagle-1.0.0.6 and eleganteagle-1.2.0.1

**Comment by Far00K** [comment]
This is just a theory but if they have different versions of a software in the same place it can mean that is all the hacking tools, or is it just a one piles of tools for one specified type of hacking or hacking a type of victim.

**Comment by marctmiller** [comment]
anyone scouring this code thinking that it's out here cuz muh russian
hacker or shadow brokerage duped nsa is delusional

they are years if not decades ahead of github twerps and the rest of the
open source community

waste more time learning and being constructive than watever the fuck this
shit thread is

**Comment by Far00K** [comment]
Then... what is this?

**Comment by marctmiller** [comment]
it's watever the fuck you want it to be

be an autodidact

**Comment by Far00K** [comment]
You now that the shadow brokers used github and other sites to post this files so i dont think wee are not so far behinde as a decades

**Comment by Ekultek** [comment]
Decades behind who? I don't understand what you're referring to?

**Comment by marctmiller** [comment]
there you go!

making your own assumptions!

congrats!

empirical decision making here you come!

**Comment by Far00K** [comment]
how do you that is my own assumption?

**Comment by marctmiller** [comment]
this shotty code wouldn't be here lest they wanted it to be

think of it, at a minimum, as their (if it's even wat you assume it to be)
way of forcing a step-up in their own game

On Apr 9, 2017 18:02, "Thomas Perkins" <notifications@github.com> wrote:

Decades behind who? I don't understand what you're referring to?


> On Apr 9, 2017, at 5:56 PM, Farook <notifications@github.com> wrote:
>
> You now that the shadow brokers used github and other sites to post this
files so i dont think wee are not so far behinde as a decades
>
> —
> You are receiving this because you were mentioned.

> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/x0rz/EQGRP/issues/10#issuecomment-292819892>, or mute
the thread

**Comment by Ekultek** [comment]
@marctmiller was that directed towards me?

**Comment by Far00K** [comment]
no it was directed to @marctmiller

**Comment by marctmiller** [comment]
>You now that the shadow brokers used github and other sites to post this
files so i dont think wee are not so far behinde as a decades

i don't shit and you assumed for me

stop that

On Apr 9, 2017 18:05, "Farook" <notifications@github.com> wrote:

how do you that is my own assumption?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/x0rz/EQGRP/issues/10#issuecomment-292820070>, or mute
the thread

**Comment by Tdog21** [comment]
@Far00K and @marctmiller zip this horseshit it's getting irritating. Go create a new thread and talk about it in their

**Comment by marctmiller** [comment]
are we not talking about turning off av?

and danger free?

are we in the danger zone, tdog?

**Comment by Ekultek** [comment]
@marctmiller let's break this down logically really quick. What do we know (or think we know)?

1. A hacking groups claim to fame is that they hacked an NSA archive containing a bunch of "hacking tools" that don't really do anything.
2. These tools clearly have a version control system in place or else there would not be a version number in the code.
3. These "tools" apparently where dumped in reply to Trump bombing Syria, however that doesn't make logical sense, if you wanted to let Trump know you are pissed, just dump his information instead.
4. We (think) we are missing something from these because most of the tools direct to either a certain IP address, or require a certain server name, if you run them, most of them require an IP to be initialized.
5. If this REALLY was from the NSA and was IMPORTANT to them, it would have been shut down hours ago, and we would all be being tracked for even being on here because we all made forks of it.

So what this boils down to is this, the NSA either didn't write this, or we don't have all the files.

**Comment by Far00K** [comment]
No i dident meant to irritating you. I gote just triggered by marctmiller

**Comment by Far00K** [comment]
I have an idea. We must remember that we are talking about NSA and if this was there files and it was so important they could just shut down github or the sources that are leaking the files out.

**Comment by marctmiller** [comment]
many logical fallacies here "thomas perkins"

On Apr 9, 2017 18:14, "Thomas Perkins" <notifications@github.com> wrote:

@marctmiller <https://github.com/marctmiller> let's break this down
logically really quick. What do we know (or think we know)?

   1. A hacking groups claim to fame is that they hacked an NSA archive
   containing a bunch of "hacking tools" that don't really do anything.
   2. These tools clearly have a version control system in place or else
   there would not be a version number in the code.
   3. These "tools" apparently where dumped in reply to Trump bombing
   Syria, however that doesn't make logical sense, if you wanted to let Trump
   know you are pissed, just dump his information instead.
   4. We (think) we are missing something from these because most of the
   tools direct to either a certain IP address, or require a certain server
   name, if you run them, most of them require an IP to be initialized.
   5. If this REALLY was from the NSA and was IMPORTANT to them, it would
   have been shut down hours ago, and we would all be being tracked for even
   being on here because we all made forks of it.

So what this boils down to is this, the NSA either didn't write this, or we
don't have all the files.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/x0rz/EQGRP/issues/10#issuecomment-292820537>, or mute
the thread

**Comment by Far00K** [comment]
ok...

**Comment by Tdog21** [comment]
@Far00K dont worry @marctmiller is just insecure and is trying to assert himeself

**Comment by Far00K** [comment]
Burned

**Comment by Ekultek** [comment]
@Far00K or he's just extremely dumb. It's one or the other lol.

Anyways @Tdog21 I still think we're missing some files. There's gotta be a configuration or something we don't have.

**Comment by Far00K** [comment]
I fink that why shoulde they give all the file. Maby it was just a show of to show they have the files and later they gone ask fore money for the rest.

**Comment by marctmiller** [comment]
i'm not having problems getting things i find interesting up and running

and yes you will have to write your own ____ from time to time.. and
sometimes even flip 1s or 0s

do you asshats read books or use google?

best of luck at any rate

**Comment by Far00K** [comment]
But what do you know, we dont already know (sorry for my english)

**Comment by Ekultek** [comment]
Neither, obviously I'm dumb. I just get paid to do this.

**Comment by Far00K** [comment]
ok... Im meant the questien to marctmiller

**Comment by Far00K** [comment]
And what do you meen you get paid to do this @Ekultek

**Comment by Ekultek** [comment]
@marctmiller nobody said anything about not being able to run them. They just don't really do anything when you do run them.

**Comment by marctmiller** [comment]
esr would be ashamed (well, sorta)

whoever's paying you isn't getting their $'s worth

**Comment by NoahGWood** [comment]
@Ekultek 
The NSA would have no legal right to "track you down" and van you for forking this github or scouring the source. If you do not hold security clearance you are not prohibited from viewing classified/secret/top-secret/xyasdf information that was released publicly, even if the information is still classified and the people who released it did so illegally.

If you DO hold a security clearance on the other hand, you could get in trouble for viewing these files.

Also, I wouldn't say they don't do anything. There is exploits, all manner of rootkits, and more binaries than a single person could pour through in a week. The fact that a few python scripts require connecting back to other servers is irrelevant. The exploits are still there and still able to be reverse engineered.

**Comment by Ekultek** [comment]
I agree, but since when has the NSA done anything legally? Also I didn't know you could get in trouble if you had a clearance?

**Comment by Far00K** [comment]
I look in to a file and one of them, hade a instruction

**Comment by Far00K** [comment]
It can meen that it's instrution to hack something

**Comment by Chnkr** [comment]
Thanks for filling up my mailbox with your edgy comments 👍

**Comment by Far00K** [comment]
De nada

**Comment by pussyknit** [comment]
Are you guys kidding me with this shit? Of course there are different versions. The NSA keeps a retarded index of hardware profiles with work arounds and exploits for each type of hardware profile. Shit this stuff is fucking played out like acid wash. This thread was a Yawn fest. You guys should try taking drugs or get some HOOKERS and loosen up. This shit is real but these versions are not the latest. This is old shit. BTW fuck working for those commie fucks. They wouldn't hire anyone from this thread. You ladies would never make the cut. These clowns only pull internet consortium, ivy league motherfuckers that are robots with a spotless history. You chronic masterbaters need to stay in school. Maybe in about forty years you can get a job at the NSA pushing a broom. Fuck the pigs. America is burnt

**Comment by Atavic** [comment]
@Dawnspire3000 Just close this trollfest of an issue, please.

**Comment by Atavic** [comment]
Thank you.

**Comment by ghost** [comment]
If you want to hack the NSA, best bet is start here:

NSA dotgov exposes their Oracle Peoplesoft login ~ LOL

http://i.magaimg.net/img/10yu.png

As recently as May, you could have used this Peoplesoft RCE to pwn NSA dotgov ~ LOL

http://i.magaimg.net/img/10yt.png

Hint: Google site:nsa.gov inurl:psp

http://i.magaimg.net/img/10yv.png

I encourage you to poke around NSA dotgov, there's all kinds of little fuckups they ignored.
If your Autism can exceed the NSA's autism, you'll find something they put in that they didn't know that you could do.
More important than any exploits, I strongly encourage you to read their small mountain of pdfs of declassified historical documents covering every topic from Nerd-Heaven imaginable.
It doesn't matter which pdfs you read, nor which order, just pick anything you find personally interesting and start digging in.

Btw, you have my full permission to hack NSA dotgov anyway that you can find--if you're clever enough to slap the face of supreme hubris from jackasses who said "Nothing is Beyond Our Reach" then you deserve all the Street Fame for cuckshaming them.

Don't be intimidated by their $72 BILLION Black Budget and GODMODE. At least 97% of it is PURE WASTE, and those drooling mouth breathing gubbmint GS-13's could't tell their asshole from a hole in the ground unless there was an Official Manual with a list of checkboxes for them to blindly obey how to do it.
Always remember the Federales can barely light up 2 neurons between themselves and that's by design.
Do you want a goddamn hyper efficient govt that could go Super-1984 in a snap of the fingers?
Hell no! Slapstick redundancy, gross incompetence, $600 Park outhouse toilet seats, $1000 claw hammers and "accidentally losing" $2.2 BILLION in Hummers to ISIS in Mosul is the only thing keeping us Free from a Cyber Dystopian Orwellian Nightmare!

Anyways, so I tweeted more about how to hack NSA:

http://i.magaimg.net/img/10yx.png

And more...

http://i.magaimg.net/img/10yz.png

And then ironically, within minutes of tweeting, I got suspended ~ LOL

http://i.magaimg.net/img/10z0.png

Which I take as a badge of honor btw. If I was deemed enough of a cyber threat to be targetted in real-time and shut_it_down_the_goyim_know.jpg just for fucking around with Google Dorking and poking NSA dotgov with a stick for fun during an idle 15 minutes, imagine the real exploitation that's possible if you properly case the joint and bring your full hamburgler tool kit?

Perhaps this little incident had something to do with a not very talkative FBI Special Agent calling me a month later and asking me if I knew anything about the Shadowbroker and a plot to re-purpose EQGRP viruses to crash the entire Internet just to hit glass jaw NSA on the chin.

(btw just in case jerks don't like my mean words here, does it look like i care if this throw away GH acct also gets suspended? Once you're marked as Enemy of the State like me, every acct you have gets suspended every week, which you Deal_With_It.gif and interpret your own censorship as damage and route around it.)
